apiVersion: v1
kind: Namespace
metadata:
  name: reconx
  labels:
    app.kubernetes.io/part-of: reconx
---
apiVersion: v1
kind: Namespace
metadata:
  name: reconx-monitoring
  labels:
    app.kubernetes.io/part-of: reconx
